### ISSUE TITLE
[PROPOSAL] Add Sean Li as a Maintainer

### ISSUE THREAD

**Issue by macohen** [opensearch-project/search-processor#127]
Current maintainers voted to add Sean Li (@sejli) as a maintainer on this repository. @opensearch-project/admin, can you please add him to the maintainers in the collaborators list on the repo? 

Thanks,
Mark

**Comment by dblock** [comment]
@macohen PR a change into MAINTAINERS/CODEOWNERS and don't merge until that's done

**Comment by msfroh** [comment]
It looks like I already merged the PR 3 days ago (before the response from @dblock).

**Comment by macohen** [comment]
@sejli can you check your permissions on the repo? Can you assign issues, add/remove labels, etc.?

**Comment by sejli** [comment]
Still don't have permissions. (Checking to see if I can create a branch)

**Comment by sejli** [comment]
@opensearch-project/admin could we get some eyes on this? I still don't have maintainer status

**Comment by gaiksaya** [comment]
Added @sejli as the maintainer.

@macohen @msfroh The permission status is below:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/61760125/233182338-40ca547d-1f43-4e97-9a95-e6e51aeb1a90.png">

I believe we need to clean up or update the maintainers/codeowners file. Let me know how to proceed.
Thanks!

**Comment by sejli** [comment]
Thanks for the quick response @gaiksaya! Updates have already been made to `MAINTAINERS.md` and `.github/CODEOWNERS` in #128. Are there any more action items?

**Comment by gaiksaya** [comment]
`anirudha` is not in the maintainer or codeowner list so will be removing him. If there any concerns or this change needs to be reverted let me know.
Thanks!

Updated list:
![image](https://user-images.githubusercontent.com/61760125/233228358-ac1c693b-fbb8-4bde-948c-1a5d810bce3e.png)

**Comment by macohen** [comment]
thanks, all! please close this if you've verified, @sejli? are you able to create/delete a branch now?

**Comment by sejli** [comment]
Closing since permissions have been granted and files have been updated.
